# Unified Configuration File for Strategy Explainer
# Consolidates all configuration into a single file
# Environment variables can override values using ${ENV_VAR_NAME} syntax

# Application Settings
app:
  debug: false
  log_level: "INFO"
  
# API Configuration (use environment variables for secrets)
api:
  openai_api_key: "${OPENAI_API_KEY}"
  alpha_vantage_api_key: "${ALPHA_VANTAGE_API_KEY}"
  newsapi_key: "${NEWSAPI_API_KEY}"
  finnhub_key: "${FINNHUB_API_KEY}"

# Data Configuration
data:
  source: "${DATA_SOURCE:yfinance}"  # Default to yfinance if not set
  benchmark: "${DEFAULT_BENCHMARK:SPY}"
  cache_duration_minutes: 60
  default_symbols: ["AAPL", "MSFT", "GOOGL"]  # Default symbols for data loading examples
  max_retries: 3  # Maximum retry attempts for data fetching
  timeout_seconds: 30  # Timeout for data requests
  
# File Paths
paths:
  data_dir: "data"
  cache_dir: "data/cache"
  outputs_dir: "backend/outputs"
  reports_dir: "backend/outputs/reports"
  charts_dir: "backend/outputs/charts"

# Streamlit Configuration
streamlit:
  theme: "${STREAMLIT_THEME:light}"
  port: 8501

# Strategy Definitions (from strategies.yaml)
strategy_definitions:
  momentum:
    simple_momentum:
      name: "Simple Momentum"
      description: "Basic momentum strategy using price rate of change"
      parameters:
        lookback_period: 20
        threshold: 0.02
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.10
        
    rsi_momentum:
      name: "RSI Momentum"
      description: "Momentum strategy using RSI indicator"
      parameters:
        rsi_period: 14
        rsi_buy_threshold: 30
        rsi_sell_threshold: 70
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.10

  mean_reversion:
    bollinger_bands:
      name: "Bollinger Band Mean Reversion"
      description: "Mean reversion using Bollinger Bands"
      parameters:
        bb_period: 20
        bb_std_dev: 2
        position_size: 0.1
        stop_loss: 0.03
        take_profit: 0.05
    
    z_score:
      name: "Z-Score Mean Reversion"
      description: "Mean reversion using Z-Score of price"
      parameters:
        lookback_period: 50
        z_threshold: 2.0
        position_size: 0.1
        stop_loss: 0.03
        take_profit: 0.05

  breakout:
    channel_breakout:
      name: "Channel Breakout"
      description: "Breakout strategy using price channels"
      parameters:
        channel_period: 20
        breakout_threshold: 0.01
        position_size: 0.1
        stop_loss: 0.04
        take_profit: 0.08
    
    volume_breakout:
      name: "Volume Breakout"
      description: "Breakout strategy with volume confirmation"
      parameters:
        price_period: 20
        volume_period: 10
        volume_multiplier: 1.5
        position_size: 0.1
        stop_loss: 0.04
        take_profit: 0.08

# Strategy Engine Configuration (from strategy_config.json)
strategies:
  sma_ema_rsi:
    enabled: true
    parameters:
      fast_period: 10
      slow_period: 50
      rsi_period: 14
      use_rsi_filter: true
      rsi_oversold: 30
      rsi_overbought: 70

  crossover:
    enabled: true
    parameters:
      fast_period: 10
      slow_period: 30

  rsi:
    enabled: true
    parameters:
      rsi_period: 14
      oversold_threshold: 30
      overbought_threshold: 70

  volatility_breakout:
    enabled: true
    parameters:
      atr_period: 14
      volume_period: 20
      breakout_multiplier: 2.0
      volume_multiplier: 1.5

  channel_breakout:
    enabled: true
    parameters:
      channel_period: 20
      breakout_threshold: 0.02

  volume_breakout:
    enabled: true
    parameters:
      volume_period: 20
      volume_multiplier: 2.0
      price_change_threshold: 0.01

  bollinger_mean_reversion:
    enabled: true
    parameters:
      bb_period: 20
      bb_std_dev: 2.0
      entry_std_dev: 2.0
      exit_std_dev: 0.5

  zscore_mean_reversion:
    enabled: true
    parameters:
      lookback_period: 50
      z_entry_threshold: 2.0
      z_exit_threshold: 0.5

  rsi_mean_reversion:
    enabled: true
    parameters:
      rsi_period: 14
      rsi_oversold: 20
      rsi_overbought: 80
      rsi_exit_level: 50

  mean_reversion_combo:
    enabled: true
    parameters:
      bb_period: 20
      bb_std_dev: 2.0
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      require_both_signals: true

  sentiment_mean_reversion:
    enabled: true
    parameters:
      bearish_threshold: -0.5
      bullish_threshold: 0.5
      sentiment_period: 3
      require_price_confirmation: true
      price_lookback: 5

# Backtest Configuration
backtest:
  initial_capital: 10000
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  commission: 0.001
  slippage: 0.0005

# Risk Management
risk_management:
  stop_loss_pct: null
  take_profit_pct: null
  max_drawdown_pct: 0.20
  position_size_pct: 1.0
  max_position_per_trade: 0.25
  risk_free_rate: 0.02

# Batch Testing Configuration
batch_testing:
  default_tickers: ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA"]
  include_combinations: true
  combination_methods: ["majority", "unanimous", "any"]
  save_results: true
  output_directory: "backend/outputs"

# Batch Backtest Configuration - Hyperparameter Sweep Parameters
batch_backtest:
  # Asset universe for cross-validation
  tickers: ["AAPL", "MSFT", "SPY", "QQQ", "TSLA"]
  
  # Stop loss levels (as percentages) - null means no stop loss
  stop_losses: [0.02, 0.05, 0.10, null]  # 2%, 5%, 10%, or null
  
  # Take profit levels (as percentages) - null means no take profit
  take_profits: [0.05, 0.10, 0.20, null]  # 5%, 10%, 20%, or null
  
  # Position sizing (percentage of capital per trade)
  position_sizes: [1.0, 0.75, 0.5]  # 100%, 75%, 50% of capital
  
  # Maximum portfolio drawdown limits - null means no limit
  max_drawdowns: [null, 0.15, 0.20, 0.25]  # null, 15%, 20%, 25% max portfolio drawdown
  
  # Backtest configuration
  capital: 10000  # Starting capital
  start_date: "2020-01-01"  # Backtest start date
  end_date: "2024-01-01"    # Backtest end date
  
  # Output configuration
  output_directory: "backend/outputs"
  
  # Quick mode configuration (for testing)
  quick_mode:
    tickers: ["AAPL", "SPY"]
    stop_losses: [0.05, null]
    take_profits: [0.10, null]
    position_sizes: [1.0, 0.5]
    max_drawdowns: [null, 0.20]
    
  # CSV output header configuration
  csv_header: [
    "ticker", "stop_loss_pct", "take_profit_pct", "max_drawdown_pct", 
    "position_size_pct", "total_return", "sharpe_ratio", "max_drawdown", 
    "num_trades", "win_rate", "avg_trade_return", "total_profit", 
    "total_loss", "profit_factor", "calmar_ratio", "kelly_criterion", 
    "run_status", "error_message"
  ]

# Advanced Features
advanced_features:
  regime_detection:
    enabled: true
    default_method: "sma_slope"
    parameters:
      sma_slope:
        sma_period: 50
        slope_threshold: 0.0001
      atr_volatility:
        atr_period: 14
        volatility_threshold: 75
      vix_levels:
        low_vix: 15
        high_vix: 25

  sentiment_overlay:
    enabled: true
    default_provider: "mock"
    providers:
      mock:
        parameters: {}
      newsapi:
        api_key: "${NEWSAPI_API_KEY}"
        parameters:
          sentiment_threshold: 0.1
          article_limit: 10
      finnhub:
        api_key: "${FINNHUB_API_KEY}"
        parameters:
          sentiment_threshold: 0.1

# Performance Metrics
performance_metrics:
  primary_metric: "sharpe_ratio"
  secondary_metrics: ["cagr", "max_drawdown", "win_rate", "profit_factor"]
  benchmark: "SPY"
  risk_free_rate: 0.02

# Global Strategy Settings
global_settings:
  default_timeframe: "1d"
  min_trade_size: 100
  max_position_size: 0.2
  commission_rate: 0.001
  slippage_rate: 0.0005
  trading_days_per_year: 252

# Default Strategy Parameters
defaults:
  lookback_period: 20
  threshold: 0.02
  position_size: 0.1
  stop_loss: 0.05
  take_profit: 0.10

# UI Configuration - Charts and Styling
ui:
  charts:
    colors:
      primary: "#1f77b4"
      secondary: "#ff7f0e"
      success: "#2ca02c"
      danger: "#d62728"
      warning: "#ff7f0e"
      info: "#17a2b8"
      equity_line: "#2E86AB"
      benchmark_line: "#A23B72"
      buy_signal: "#00C851"
      sell_signal: "#FF4444"
      volume_bar: "#A8DADC"
      background: "#FFFFFF"
      grid: "#F0F0F0"
      
  metrics_cards:
    styling:
      positive_color: "#00C851"
      negative_color: "#FF4444"
      neutral_color: "#33B5E5"
      background_color: "#FFFFFF"
      border_color: "#E0E0E0"
      text_color: "#333333"
      header_color: "#666666"
      
  layout:
    sidebar_width: 300
    main_content_padding: 20
    chart_height: 400
    card_height: 150 