# Strategy Configuration File
# Define parameters for different trading strategies

momentum:
  simple_momentum:
    name: "Simple Momentum"
    description: "Basic momentum strategy using price rate of change"
    parameters:
      lookback_period: 20
      threshold: 0.02
      position_size: 0.1
      stop_loss: 0.05
      take_profit: 0.10
    
  rsi_momentum:
    name: "RSI Momentum"
    description: "Momentum strategy using RSI indicator"
    parameters:
      rsi_period: 14
      rsi_buy_threshold: 30
      rsi_sell_threshold: 70
      position_size: 0.1
      stop_loss: 0.05
      take_profit: 0.10

mean_reversion:
  bollinger_bands:
    name: "Bollinger Band Mean Reversion"
    description: "Mean reversion using Bollinger Bands"
    parameters:
      bb_period: 20
      bb_std_dev: 2
      position_size: 0.1
      stop_loss: 0.03
      take_profit: 0.05
  
  z_score:
    name: "Z-Score Mean Reversion"
    description: "Mean reversion using Z-Score of price"
    parameters:
      lookback_period: 50
      z_threshold: 2.0
      position_size: 0.1
      stop_loss: 0.03
      take_profit: 0.05

breakout:
  channel_breakout:
    name: "Channel Breakout"
    description: "Breakout strategy using price channels"
    parameters:
      channel_period: 20
      breakout_threshold: 0.01
      position_size: 0.1
      stop_loss: 0.04
      take_profit: 0.08
  
  volume_breakout:
    name: "Volume Breakout"
    description: "Breakout strategy with volume confirmation"
    parameters:
      price_period: 20
      volume_period: 10
      volume_multiplier: 1.5
      position_size: 0.1
      stop_loss: 0.04
      take_profit: 0.08

# Global settings
global:
  default_timeframe: "1d"
  min_trade_size: 100
  max_position_size: 0.2
  commission_rate: 0.001
  slippage_rate: 0.0005 