# Streamlit Secrets Configuration
# This file should contain your actual API keys and sensitive data
# Copy values from your .env file here for Streamlit deployment

# API Keys
OPENAI_API_KEY = "your_openai_api_key_here"
ALPHA_VANTAGE_API_KEY = "your_alpha_vantage_api_key_here"

# Database URLs (if needed)
# DATABASE_URL = "your_database_connection_string"

# Other sensitive configuration
# SECRET_KEY = "your_secret_key_here" 